### ISSUE TITLE
check length requirements of wep key

### ISSUE THREAD

**Issue by mstiles-shearwater** [InfamousSYN/rogue#10]
Currently the WEP key has no length checks which result in errors when the expected lengths are not met.

> \# A key may be a quoted string or unquoted hexadecimal digits.  
\# The key length should be 5, 13, or 16 characters, or 10, 26, or 32  
\# digits, depending on whether 40-bit (64-bit), 104-bit (128-bit), or
\# 128-bit (152-bit) WEP is used.

**Comment by InfamousSYN** [comment]
implemented in commit [df2a0a3](https://github.com/InfamousSYN/rogue/commit/df2a0a3f2bd65d37ffe1ae3f546063bfaded014a)
