### ISSUE TITLE
wlan1: interface state UNINITIALIZED->DISABLED

### ISSUE THREAD

**Issue by jepunband** [InfamousSYN/rogue#24]
Hi, i'm using a supported wireless card that supports Monitor and AP mode , don't have issues with this card using other wireless tools that requires AP mode.
But i get error with this tool : 

Configuration file: /home/gill/rogue/tmp/hostapd-wpe.conf
ACS: Automatic channel selection started, this may take a bit
wlan1: interface state UNINITIALIZED->ACS
wlan1: ACS-STARTED 
Configuration file: /home/gill/rogue/tmp/hostapd-wpe.conf
wlan1: INTERFACE-DISABLED 
nl80211: Could not configure driver mode
nl80211: deinit ifname=wlan1 disabled_11b_rates=0
nl80211 driver initialization failed.
wlan1: interface state UNINITIALIZED->DISABLED
wlan1: AP-DISABLED 
wlan1: CTRL-EVENT-TERMINATING 
hostapd_free_hapd_data: Interface wlan1 wasn't started
ACS: Failed to request initial scan
ACS: Failed to request scan
Interface initialization failed
wlan1: interface state ACS->DISABLED
wlan1: AP-DISABLED 
ACS: Failed to start
wlan1: AP-DISABLED 
hostapd_free_hapd_data: Interface wlan1 wasn't started
nl80211: deinit ifname=wlan1 disabled_11b_rates=0
wlan1: interface state DISABLED->DISABLED
wlan1: interface state DISABLED->DISABLED
wlan1: AP-DISABLED 
wlan1: CTRL-EVENT-TERMINATING 
hostapd_free_hapd_data: Interface wlan1 wasn't started

**Comment by InfamousSYN** [comment]
With hostapd attempting to do ACS and without seeing the command configuration being used, the two likely causes are:
1. the `--channel` flag wasn't set 
2. or it was but the channel selected isn't supported on the hardware a channel was selected which isn't supported within your region of the world

`--country` flag allows you to manipulate the regulatory domain applied the hardware at runtime. The default domain configured on hardware is typically `00` which is `world` domain and is the most restrictive. Using `--country BO` will change the wireless regulatory domain to Bolivia which is one of the most least restrictive regulatory domains, as such hardware is typically allowed transmit on most WIFI channels.
