### ISSUE TITLE
Public or personal use?

### ISSUE THREAD

**Issue by anoduck** [InfamousSYN/rogue#44]
Is this repo for public or private use? Is this being maintained anymore?

Tried running it several times, and there are several dependencies that are not mentioned in the docs. For example: nmcli, and a working resolv.systemd configuration. 

Were you aware that it overwrites `/etc/resolve.conf` with a symbolic link to `/etc/systemd/resolv.conf` or some reasonable facsimile there of?

**Comment by InfamousSYN** [comment]
Hi anoduck, love the energy. 

To answer your questions:
- Yes, this project is still maintained and is for public use, 
- rogue itself, much like its root [eaphammer ](https://github.com/s0lst1c3/eaphammer) had always been intended to run as a CLI wrapper around the workhorse packages (hostapd-wpe, bind-dns and  isc-dhcp), 
- also both project have always been intended to run a kali linux platform, hence the various routines for controlling nmcli.

With that said, i can definitely update the documentation to clearly state the assumptions of it being used as a CLI used on a kali linux platform to help address any further confusion.

**Comment by anoduck** [comment]
Wow, and you are like a really nice guy. Thanks for telling me about eaphammer, and thanks for the response.

My biggest hurdle is finding a means to allow the SSH port open and reachable, because I am ssh tunneling into a remote host. Some of this, has to do with the nature of the software, and some of it has to do with what I mentioned. I have had a little success with autossh, but my most recent few attempts were no tamale.

Everybody does things differently and are comfortable doing different things. I have run all my implementations on Kali Rolling Release, and even installed a bare metal copy a few days ago specifically for this. I come from the OpenBSD tradition of things, and if not running Kali, I usually I am working with alpine. Saying all of this, is an obtuse way of politely saying I am not even sure which package in Kali provides `nmcli`. Is it located in `/usr/libexec` that might not be in my PATH? 

I feel I have rambled on for too much now, thanks for the response.

**Comment by anoduck** [comment]
@InfamousSYN You know those moments when you make things unnecessarily difficult for yourself?

Yeah, it happens. Thanks for being a nice dude.
