### ISSUE TITLE
Unable to install freeradius-wpe

### ISSUE THREAD

**Issue by weuroi578** [InfamousSYN/rogue#7]
After attempting to install the Rogue Toolkit on an updated version of Kali I receive the following error:

> The following packages have unmet dependencies:
>      freeradius-wpe : depends: libperp5.26 (>= 5.26.0~rc1) but it is not installable
> E: Unable to correct problems, you have held broken packages.

I've attempted to install this version but there is no longer an installation candidate. I should also mention that libperl5.28 is already install on my Kali machine. 

Has anyone else come across this problem?

**Comment by InfamousSYN** [comment]
The error you're receiving is a result of an issue with your environment, if the issue persists make sure that you've done a full upgrade of the distribution before installation. The issue may be resolved using the `--fix-missing` and `--fix-broken` aptitude flags. I've confirmed that rogue is able to be installed in kali 2018.4, which has recently been released.  

Alternatively, if you use Vagrant and Chef to provisioning your environments, I've recently released a cookbook to automate the provisioning process. [https://github.com/InfamousSYN/Cookbook-Wireless/](https://github.com/InfamousSYN/Cookbook-Wireless/)

_Note: the target OS for the cookbook is Ubuntu 18.04 not Kali._

**Comment by InfamousSYN** [comment]
`libperl` is not specifically need by the `hostapd-wpe`, `freeradius-wpe` or `isc-dhcp-server` packages. 

When installing rogue in a live VM based off the 2018.4 image, `libperl5.26` did not get upgrade for me, attached the output from the rogue setup in the live VM for more information. [install.txt](https://github.com/InfamousSYN/rogue/files/2564749/install.txt)
